\begin{center}
\textbf{\textit{Acknowledgements}}
\end{center}
* Eunseo
** care and understanding
** inspiration and encouragement
** patience and enormous efforts spent
that prevent me from being disengaged by the very hard but interesting questions.

There is no proper words for me to express my deep gratitude toward my major thesis advisor Dr. Eunseo Choi. He has changed my life in a very positive way. From him, I have learned what a great researcher and educator should be like. It is because of his unfailing care and understanding that have given me the courage to persevere, to carry on during the darkest days as an international student far away from home. It is his vivid and interesting lessons that have inspired me so much that I want to devote my career into geodynamic modeling. It is his numerous inspiration and encouragement that has motivated me to work super hard (enjoy in the same time) on the hard problems. It is his patience to guide me through my endless silly questions that has led me to an independent researcher. It is his altruistic share that has provided me with great chances to learn from many great researchers from websites, references, books and meetings. Blessings from Eunseo, my role model, are uncountable. I will keep them in mind and try my best to relay the torch.  

Discussing results and learning from his way of thinking has been my happiest times during this two year studies in the United States. His courses, Geodynamics and Global Geophysics has stimulate my pure interests toward the field. 
\\
* Committee members
To the other two committee members, Dr. Christine Powell and Dr. Jer-ming Chiu, for their guidance and advice during many committee meetings. For their interesting courses.
\\
* CERI professors, staff, students
To Center for Earthquake Research and Information and University of Memphis, thank a lot for providing me this great chance to study here with full tuition and graduate research assistanship. It is this kind support that has made my two year studies at this great institution possible. To all the faculties taught me courses and staff Josephine provided me a very pleasant, tidy and clean place for doing research and studying. 
\\
* To Center for Writing and Communication staff: Bill Schraufnagel
* To Tianhe2 super computer center, thank a lot for the support from National Supercomputer Center in Guangzhou. For about 200k Sus.
\\
* To Dr. Jie Liu and Dr. Ke Zhang, for kindly sharing their computing resourses on Tianhe2.
\\
* To Dr. Gu Cheng,
\\
* To Shengfang Chen and Lijie Lyu 
\\
