* To Eunseo
** from Teaching award nomination letter for Eunseo, Oct. 7, 2014
I took Professor Choi's Global Geophysics and Geodynamics. He is also my research advisor. I enjoy every lesson he taught. Under his guidance, I developed so deep love and pure interests toward science and research that I want to devote my life as a scientist.

His courses are vivid, logical and helpful. Each lesson is well prepared. Theory and examples (e.g. interesting in-course experiments) are combined to help us better understand the topic. Whenever I had a question, he will answer patiently (I always feel being respected by such a respectable scientist).  In addition, he is so knowledgable that he is always able to refer me to some key references to the problem I was confused about.

In conclusion, Eunseo is the best professor I ever met. He enlightens me deeply. He is my role model.

** Thank you letter to the Best Advisor Ever, Nov. 25, 2014
Dear Eunseo,

You might not realize that you are one of the most important person in my life. I didn’t realize how deeply you have changed my life in a positive way until I look back and count all the blessings from you : ) Here, taking advantage of the Thanksgiving, I would like to express my great gratitude toward you!

Scene of several topics to choose on the right bottom corner of your white board is just like yesterday, when I first went into your office. You warmly welcomed me and patiently explained to me each of the topics and encouraged me to choose what interests me most. I chose “M-factor”. (2013. Dec.)
Uncountable times when I went into your office feeling upset for that I know nothing and things are very hard to learn, you always understand me and patiently teach me and guide me what to do. You never complain about my buoyant trivial questions, you kindly share with me whatever cool things you know in a way I can digest.
During the hardest time when I lost my life goal and lost my love, you didn’t push me into work, you understand me and even helped me think about what to do and give me advices in coming back to China retrieving my girl. (2014. May)
It’s your word that “MIT people are trying to do ‘M factor’ in 3D too, but they will not be as early as ours, and it is your job to do it, Xiaochuan.” has inspired, encouraged and motivated me so much that has lead to who I am now. (2014.3.27)
It’s your word that “ You are up to the stage on the plateau of learning curve, begin to think and solve problem independently like a phD. does” really inspired me a lot. (2014.08.10)
You shared with me how to study continuum mechanics through www.continuummechanics.org, you introduced me C, Latex, git, emacs, SNAC, FLAC, you provided me a chance to utilize world rank NO.7 Supercomputer Stampede and share with me how to study them. It is you that introduced me to (Tucholke et al., 08); (Buck et al., 05) papers and help me to understand those papers line by line that have initiated my research (Without your patient and kind guidance, it is impossible for me to do research in such a fascinating area—Geodynamics modeling and luckily developed deep love into it in which I can spend all my time immersed and enjoyed). Only by working with you, can I—a naive fall behind young fish have the chance to go to AGU.
When I was found living in CERI, you didn’t try to accuse, you totally understand me and told me young Korean male students are encouraged to do so. Later you try to help me on finding an office and a safe place to live.  (2014 Oct.)
Finally, of course, your courses (Global Geophysics, Geodynamics) are wonderful. They provided me a chance to learn a lot of very interesting things. Your teaching style is perfect for me, fulfilled the two most important criteria for a wonderful teacher in my mind, one is inspiring students’ interests, the other is providing them methods or tools for pursuing those interests.

Please forgive my poor writing skills that I cannot fully express my heart feeling toward Eunseo. I still want to say, however, literally, without you, Xiaochuan’s life will not like what it is now. You change it positively, for which, I will always keep in mind and feeling grateful. In the future, I hope I will also be able to do the same things to my ‘students’ as my role model—Eunseo has done on me.
Sincerely yours,

Xiaochuan Tian 
