* Abstract
* Introduction
** Review of Literature
*** TODO clarify and draw mindmap for relation between the four factors for controlling the topography. Find original refs for each relationship.

- 1 magmatic supply :: Is affected by spreading rate, thermal structure and whether hot plume presents. (partial melting is a passive process)  
     *ref*:
     It releases tectonic stress.
- 2 hydrothermal circulation :: Are affected by faulting. Highly affects the thermal structure. 
     *ref:*
- 3 tectonic strain :: Affected by spreading rate and magmatic supply. Direct reason for normal faulting. And faulting is the first-order control facotr for the topography.   
     *ref:*
- 4 spreading rate :: mainly affected by far field slab pull, ridge push(magma supply) is second order. Affect magmatic supply, hydrothermal 
     *ref:*
They are interelated, the relation is very complex. But it is essential in understanding the research question.

** Statement of Research Purpose
* Methods
** Method of approach
** Model Setup
** Parameters to control
* Results (Direct observation without much logical reasoning, more objective)
** Reference model
*** Constant M88
** Main characteristics of the models (order from most frequently happen behavior)
*** Location of termination (M28LinT1)
**** Where the term "termination" shows up
- Canales 2004  :: Seismic reflection imaging of an oceanic detachment fault: Atlantis megamullion
- Escartin 2008 (Nature) :: Central role of detachment faults in accretion of slow-spreading oceanic lithosphere.
- choolmeesters 2012 G Cube :: The cooling history and the depth of detachment faulting at the Atlantis Massif oceanic core complex
- Escartin 2003 G cube :: Constraints on deformation conditions and the origin of oceanic detachments: The Mid-Atlantic Ridge core complex at 15°45′N
Dick 2010 :: Mantle Melting, Melt Transport, and Delivery Beneath a Slow-Spreading Ridge: The Paleo-MAR from 23 15'N to 23 45'N
*** geometry of troughs inside the median valley(find a term for it or define myself) (M28LinT1)
mostly refer to fast spreading ridges. But trough inside the median valley make sense.

*** Second Fault
*** Fault Alternation (? better name of it (ask brian, trevor)) (alternate is perfect fit by searching dictionary.com 1 and 3 item)
 1. to interchange repeatedly and regularly with one another in time or place;
 2. to take turns
**** Trade-off between bending and weakening
**** Alternating on conjugate plate
**** Effect of along ridge-axis couplin

*** Cut-Back
*** Corrugation
**** Corrugation due to anastomosing
**** Corrugation due to asynchronous in faulting

** Effects of the functional forms of M variation
** Effects of the weakening rate
** Effects of the range of M variation
* Discussion (Can include many logical reasoning and discussion on the results with including other people work and your reasoning)
** Summary of Results
** Comparing model results with nature observation
*** Location of termination
*** Geometry of trough
*** Inward fault jump
*** Fault Alternation
*** Mass wasting
*** Hourglass shape of median valley
*** Corrugations and mullion structures
** Difference between 3D and 2D previous studies (withhold)
*** 2D cannot produce corrugation
*** 2D cannot produce cut-back (think about the along ridge effect that is essential for cut-back)
*** range of M allowing OCC formation is increased, 
another way other than Olive2010 to reconcile the gap between large M and OCC (observation) and 2Dmodel M0.3~0.5 to produce OCC
** Influence of healing
** Model Limitation
** Recommendation for Future Research
* Conclusion (an abstract of the Abstract)(Basically, I did this, I found that.)
Only describe the finding. dif to abstract that abs is about the whole work with motivation ....

I did this, I found that.
